[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true #This means you will allow foundry to run commmands directlu on your machine
#It is recommended to keep this false and use the docker image


# See more config options https://github.com/foundry-rs/foundry/tree/master/config